{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "metaphor-php.serviceAccountName" . }}
  labels:
{{ include "metaphor-php.labels" . | nindent 4 }}
automountServiceAccountToken: true
{{- end -}}
